### ISSUE TITLE
Add GitHub Issue Template

### ISSUE THREAD

**Issue by devxprite** [7ORP3DO/realtime-chat-app#4]
Add GitHub Issue Template for Feature requests.

**Comment by MakendranG** [comment]
Hi @devXprite

I am interested in this issue. Can you plz assign me?

**Comment by devxprite** [comment]
> Hi @devXprite
> 
> I am interested in this issue. Can you plz assign me?

Sure @MakendranG

**Comment by MakendranG** [comment]
Hi @devXprite 

I have worked on this issue and raised a PR https://github.com/devXprite/Chat-World/pull/5

Kindly merge it.
